export const AllConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  QUESTIONS_GETALL_REQUEST: "QUESTIONS_GETALL_REQUEST",
  QUESTIONS_GETALL_SUCCESS: "QUESTIONS_GETALL_SUCCESS",
  QUESTIONS_GETALL_FAILURE: "QUESTIONS_GETALL_FAILURE",

  TESTS_GETALL_REQUEST: "TESTS_GETALL_REQUEST",
  TESTS_GETALL_SUCCESS: "TESTS_GETALL_SUCCESS",
  TESTS_GETALL_FAILURE: "TESTS_GETALL_FAILURE",

  ANSWERS_SETALL_REQUEST: "ANSWERS_SETALL_REQUEST",
  ANSWERS_SETALL_SUCCESS: "ANSWERS_SETALL_SUCCESS",
  ANSWERS_SETALL_FAILURE: "ANSWERS_SETALL_FAILURE",
};
